version: '2'
services:
  bobs-and-angels:
    build: 
      context: .
    args:
      VERSION: 0.15.32
    image: gone/factorio:0.15.32
    volumes:
    - ./saves:/factorio/saves
    ports:
    - 34197:34197/udp
    - 27015:27015/tcp


